// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbuwpbxewofndxptvvuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidXdwYnhld29mbmR4cHR2dnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzkwNDIsImV4cCI6MjA2Mzg1NTA0Mn0.C44qu0Nb8T6t2LTe1LQEqf_CDkAeLZlEgy_QgJmr7YI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);